from lru_cache import LRUCache

lru = LRUCache(5)
lru.set(1, 1)
lru.display()
lru.set(1, 4)
lru.display()
lru.set(2, 5)
lru.display()
print(lru.get(1))
lru.display()
lru.set(3, 6)
lru.display()
lru.set(4, 7)
lru.display()
lru.set(5, 8)
lru.display()
lru.set(6, 9)
lru.display()
print(lru.get(4))
lru.display()
lru.get(3)
lru.display()
lru.set(1, 10)
lru.display()
lru.set(7, 14)
lru.display()
print(lru.get(5))
print(lru.get(0))
