from search_tree_mod import Node
from search_tree_mod import SearchTreeMod

# stm = SearchTreeMod([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# stm.display()
# stm.delete(1)
# stm.display()
# stm.delete(3)
# stm.display()
# stm.delete(6)
# stm.display()
# stm.delete(0)
# stm.display()
# stm.delete(11)
# stm.display()


stm = SearchTreeMod([5, 4, 9, 5, 7, 2, 2])
stm.display()
stm.delete_multiple([1, 3, 6])
stm.display()
stm.delete(5)
stm.display()
stm.delete(2)
stm.display()
stm.delete(2)
stm.display()
stm.delete(9)
stm.display()
stm.delete(5)
stm.display()
stm.delete(4)
stm.display()
stm.delete(7)
stm.display()
